POST https://node-do-zero-plg4.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 1",
    "description": "Este é o vídeo 01",
    "duration": 180
}

###

GET https://node-do-zero-plg4.onrender.com/videos

###

PUT https://node-do-zero-plg4.onrender.com/videos/3788c4f2-1553-44c5-b7c8-992e7bdd34cb
Content-Type: application/json

{
    "title": "Video 2",
    "description": "Este é o vídeo 2",
    "duration": 200
}

###

DELETE https://node-do-zero-plg4.onrender.com/videos/3788c4f2-1553-44c5-b7c8-992e7bdd34cb